
DATA:
  BATCHSIZES: 16
  DATA_DIR: ../data
  IMG_SIZE:
  - 224
  - 224
  NUM_WORKERS: 4
MODEL:
  CHECKPOINT: ''
  EPOCHS: 30
  LEARNING_RATE: 1.0e-05
  LOSS_FUNCTION: CrossEntropyLoss
  MODEL_NAME: resnet18
  NUMCLASS: 3
  OPTIM_FUNCTION: Adam
WEIGHT:
  SAVE_BEST: true
  SAVE_WEIGHT_PATH: ../weights
